import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>meldcx</title>
        <meta name="description" content="Generated by Rubiyet" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className=' text-blue-700'>meldcx</h1>
      </div>
    </>
  )
}
